// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spvbyuvrvzagtxjkrctp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwdmJ5dXZydnphZ3R4amtyY3RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzgxMDEsImV4cCI6MjA2NTU1NDEwMX0.wFzYzrU1N3EmNoMq7odCa1cl6pMiVLGmY2a-ba9pJvA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);